server:
  port: 80

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.14:1521/xe
    username: hr
    password: hr

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR
  type-aliases-package: com.example.demo
  mapper-locations: classpath:mappers/*.xml